/// Flutter icons MyFlutterApp
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
///
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Typicons, (c) Stephen Hutchings 2012
///         Author:    Stephen Hutchings
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://typicons.com/
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyFlutterApp';
  static const String? _kFontPkg = null;

  // ignore: constant_identifier_names
  static const IconData head_side_cough =
      // ignore: avoid_redundant_argument_values
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  // ignore: avoid_redundant_argument_values
  static const IconData temperatire =
      // ignore: avoid_redundant_argument_values
      IconData(0xe8f1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}

// TODO do some clean-up -> put the icons and fonts in one file if possible
class MyFlutterApp2 {
  MyFlutterApp2._();

  static const _kFontFam = 'MyFlutterApp2';
  static const String? _kFontPkg = null;

  // ignore: constant_identifier_names
  static const IconData head_side_virus =

      // ignore: avoid_redundant_argument_values
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
